update configuration/makefile

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -12,9 +12,9 @@ ac_help=
 ac_default_prefix=/usr/local
 # Any additions from configure.in:
 ac_help="$ac_help
-  --with-tcl=DIR use Tcl 8.2 binaries from DIR"
+  --with-tcl=directory containing tcl configuration (tclConfig.sh)"
 ac_help="$ac_help
-  --with-tk=DIR use Tk 8.2 binaries from DIR"
+  --with-tk=directory containing tk configuration (tkConfig.sh)"
 ac_help="$ac_help
   --disable-stubs         disable stub support"
 
@@ -530,7 +530,7 @@ fi
 
 #--------------------------------------------------------------------
 # See if there was a command-line option for where Tcl is; if
-# not, assume that its top-level directory is a sibling of ours.
+# not, assume that its top-level directory is /usr.
 #--------------------------------------------------------------------
 
 # Check whether --with-tcl or --without-tcl was given.
@@ -538,16 +538,16 @@ if test "${with_tcl+set}" = set; then
   withval="$with_tcl"
   TCL_BIN_DIR=$withval
 else
-  TCL_BIN_DIR=`cd ../../tcl8.2.3/unix; pwd`
+  TCL_BIN_DIR=/usr/lib
 fi
 
-if test ! -d $TCL_BIN_DIR; then
-    { echo "configure: error: Tcl directory $TCL_BIN_DIR does not exist" 1>&2; exit 1; }
+if test ! -e $TCL_BIN_DIR/tclConfig.sh; then
+    { echo "configure: error: Tcl configuration $TCL_BIN_DIR/tclConfig.sh not found" 1>&2; exit 1; }
 fi
 
 #--------------------------------------------------------------------
 # See if there was a command-line option for where Tk is; if
-# not, assume that its top-level directory is a sibling of ours.
+# not, assume that its top-level directory is /usr.
 #--------------------------------------------------------------------
 
 # Check whether --with-tk or --without-tk was given.
@@ -555,11 +555,11 @@ if test "${with_tk+set}" = set; then
   withval="$with_tk"
   TK_BIN_DIR=$withval
 else
-  TK_BIN_DIR=`cd ../../tk8.2.3/unix; pwd`
+  TK_BIN_DIR=/usr/lib
 fi
 
-if test ! -d $TK_BIN_DIR; then
-    { echo "configure: error: Tk directory $TK_BIN_DIR does not exist" 1>&2; exit 1; }
+if test ! -e $TK_BIN_DIR/tkConfig.sh; then
+    { echo "configure: error: Tk configuration $TK_BIN_DIR/tkConfig.sh not found" 1>&2; exit 1; }
 fi
 
 #--------------------------------------------------------------------
@@ -579,9 +579,10 @@ fi
 # Initialise installation path from prefix
 #--------------------------------------------------------------------
 
-#test "x$prefix" = xNONE && prefix=$ac_default_prefix
-TRANS_LIB=${prefix}/lib
-TRANS_BIN=${prefix}/bin
+test "x$prefix" = xNONE && prefix=$ac_default_prefix
+test "x$exec_prefix" = xNONE && exec_prefix=$prefix
+TRANS_LIB=${exec_prefix}/lib
+TRANS_BIN=${exec_prefix}/bin
 TRANS_DIR=transcriber1.4
 
 #--------------------------------------------------------------------
@@ -616,21 +617,26 @@ file=$TK_BIN_DIR/tkConfig.sh
 
 XINCLUDES=$TK_XINCLUDES
 
+SUFFIX=""
+if test -e $TK_EXEC_PREFIX/wish$TK_VERSION; then
+  SUFFIX=$TK_VERSION
+fi
+
 #--------------------------------------------------------------------
 #       Set byte order for the  systems
 #--------------------------------------------------------------------
  
-system=`uname -s`
- 
-ORDER=""
-case $system in
-    Linux*)
-        ORDER="-DLinux"
-        ;;
-    NetBSD*)
-        ORDER="-DLinux"
-        ;;
-esac
+#system=`uname -s`
+# 
+#ORDER=""
+#case $system in
+#    Linux*)
+#        ORDER="-DLinux"
+#        ;;
+#    NetBSD*)
+#        ORDER="-DLinux"
+#        ;;
+#esac
 
 #--------------------------------------------------------------------
 #       Read in configuration information generated by Snack and arrange
@@ -713,7 +719,10 @@ fi
 
 
 
+
+
 #AC_SUBST(SNACK_INC)
+
 
 
 
@@ -725,7 +734,7 @@ fi
 #AC_SUBST(ALIB)
 
 
-
+#AC_SUBST(ORDER)
 
 trap '' 1 2 15
 cat > confcache <<\EOF
@@ -888,11 +897,13 @@ s%@TCL_SRC_DIR@%$TCL_SRC_DIR%g
 s%@TK_SRC_DIR@%$TK_SRC_DIR%g
 s%@TK_LIBS@%$TK_LIBS%g
 s%@TK_DEFS@%$TK_DEFS%g
+s%@TK_PREFIX@%$TK_PREFIX%g
+s%@TK_EXEC_PREFIX@%$TK_EXEC_PREFIX%g
 s%@TRANS_LIB@%$TRANS_LIB%g
 s%@TRANS_DIR@%$TRANS_DIR%g
 s%@TRANS_BIN@%$TRANS_BIN%g
+s%@SUFFIX@%$SUFFIX%g
 s%@TCLAPI@%$TCLAPI%g
-s%@ORDER@%$ORDER%g
 
 CEOF
 EOF
